In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("test.csv")

#Check the first and last eight elements ?

In [4]:
df.head(8)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S

In [5]:
df.tail(8)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
410,1302,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
411,1303,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
412,1304,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

#Check the number of rows and columns in dataset, 
#and get some information about dataset like (mean, median, std, min and max)?

In [9]:
df.shape #We have 418 rows and 11 columns in this dataset

(418, 11)

In [10]:
df.describe() #We have statistical information of our datasets including its mean, median, std, min and max

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

#Sort the Dataframe in descending order, based on a column (Fare)?

In [43]:
df.sort_values(by=["Fare"], ascending = False)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
343,1235,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C
53,945,1,"Fortune, Miss. Ethel Flora",female,28.0,3,2,19950,263.0000,C23 C25 C27,S
69,961,1,"Fortune, Mrs. Mark (Mary McDougald)",female,60.0,1,4,19950,263.0000,C23 C25 C27,S
24,916,1,"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)",female,48.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
142,1034,1,"Ryerson, Mr. Arthur Larned",male,61.0,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
...,...,...,...,...,...,...,...,...,...,...,...
133,1025,3,"Thomas, Mr. Charles P",male,NaN,1,0,2621,6.4375,NaN,C
21,913,3,"Olsen, Master. Artur Karl",male,9.0,0,1,C 17368,3.1708,NaN,S
266,1158,1,"Chisholm, Mr. Roderick Robert Crispin",male,NaN,0,0,112051,0.0000,NaN,S
372,1264,1,"Ismay, Mr. Joseph Bruce",male,49.0,0,0,112058,0.0000,B52 B54 B56,S
152,1044,3,"Storey, Mr. Thomas",male,60.5,0,0,3701,NaN,NaN,S

#How many unique values that occur in  columns (Pclass) and (Embarked), and what is the total amount of each (Pclass) unique values ?

In [18]:
df.Pclass.unique() #There are three unique values (3, 2, 1)

array([3, 2, 1])

In [19]:
df.Embarked.unique() #There are three unique value (Q, S, C)

array(['Q', 'S', 'C'], dtype=object)

In [22]:
df.Pclass.value_counts() #Shows the number elements in of each category

3    218
1    107
2     93
Name: Pclass, dtype: int64

In [23]:
df.Embarked.value_counts() #Shows the number elements in of each category

S    270
C    102
Q     46
Name: Embarked, dtype: int64

#Rename the two columns ( Sib Sp and Sex) to (Siblings and Gender), using two different methods?

In [46]:
df_re = df.rename(columns={"SibSp": "Siblings", "Sex": "Gender"})

In [48]:
df_re.head()

,PassengerId,Pclass,Name,Gender,Age,Siblings,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

#What was the age and  of the passenger with the most expensive fare? and how many siblings the passenger with cheapest fare has?

In [108]:
# Passenger with most expensive fare
most_expensive = df_re.loc[df_re["Fare"].idxmax(), ["Age", "Siblings"]]
print("Most expensive fare passenger:\n", most_expensive)

# Passenger with cheapest fare
cheapest = df_re.loc[df_re["Fare"].idxmin(), "Siblings"]
print("\nSiblings of cheapest fare passenger:", cheapest)

Siblings
0     0.33
1     0.17
2    12.00
3     6.00
4     5.00
5    10.00
8    14.50
Name: Age, dtype: float64

In [106]:
# df2 is defined in the next cell - moved below

0       270.1074
1       329.0000
2       600.6250
3       233.8875
4       270.3250
         ...
413          NaN
414    4247.1000
415     279.1250
416          NaN
417          NaN
Length: 418, dtype: float64

#Count total tickets in each Pclass, and find each Pclass highest fare?

In [109]:
df2 = df.groupby("Pclass").agg({"Ticket": "count", "Fare": "max"})

In [112]:
# df2 is defined in the next cell - moved below

        Ticket      Fare
Pclass
1          107  512.3292
2           93   73.5000
3          218   69.5500

#Find the Average, Minimum and Maximum Fare of survived and non survived passengers

In [116]:
df.groupby("Survived")["Fare"].agg(["mean", "min", "max"])

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Elderly
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Young
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Young
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Old
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Young
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Young

#Find rows (elements) when “Embarked” column is  “C”, and then get its fare value that is less < than 100

In [114]:
df3 = df.loc[df["Embarked"] == "C"]
df4 = df3.loc[df3["Fare"] < 100]
df4

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Elderly
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,Young
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,Young
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Old
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,Young
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,Young
...,...,...,...,...,...,...,...,...,...,...,...,...
412,1304,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S,Young
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,None
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,Young
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,None
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,None

#Using apply function, customize your own algorithm to discretize the age of passengers into (Child, Young and Old), and assign it to a new column? Hint: Choose the range of age yourself

In [123]:
#Elderly 
def Get_Old_Pass(row):
    
    Age = row["Age"]
    
    if (Age>60):
        
        return "Old"
    elif(18 <= Age <= 60):
        
        return "Young"
    elif(Age<18):
        
        return "Child"

In [124]:
df["Elderly"] = df.apply(Get_Old_Pass, axis=1)

In [125]:
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Elderly
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,None
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,None
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,Old
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,None
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,None
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,None
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,None
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,None
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,None
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,None